# Generated by Django 5.2.5 on 2026-04-27 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budgetID', models.AutoField(primary_key=True, serialize=False)),
                ('catering', models.DecimalField(db_column='catering', decimal_places=2, max_digits=10)),
                ('party_supplies', models.DecimalField(db_column='partySupplies', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'ShowUp_Budgets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caterer',
            fields=[
                ('name', models.CharField(db_column='catererName', max_length=255, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_column='phoneNumber', max_length=20)),
                ('location', models.TextField(db_column='location')),
            ],
            options={
                'db_table': 'ShowUp_Caterers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('cateringID', models.AutoField(primary_key=True, serialize=False)),
                ('special_instructions', models.TextField(db_column='specialInstruction')),
            ],
            options={
                'db_table': 'ShowUp_Catering',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('id', models.AutoField(db_column='eventID', primary_key=True, serialize=False)),
                ('event_name', models.TextField(db_column='eventName')),
                ('event_description', models.TextField(blank=True, db_column='description')),
                ('date', models.DateField(db_column='date')),
                ('time', models.TimeField(db_column='time')),
                ('location', models.TextField(db_column='location')),
            ],
            options={
                'db_table': 'ShowUp_Events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dashboard.eventpost')),
            ],
            options={
                'db_table': 'ShowUp_EventPhotos',
            },
        ),
    ]
