# Generated by Django 5.0.1 on 2026-04-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('dropoff', models.TextField(default='')),
                ('pickup', models.TextField(default='')),
                ('date', models.TextField(default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('pickup_time', models.TimeField()),
                ('dropoff_time', models.TimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='carpool_posts/')),
                ('image_visibility', models.CharField(choices=[('all', 'All Users')], default='all', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
