# Generated by Django 5.2.7 on 2026-04-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.TextField(default='')),
                ('event_name', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('caterer_address', models.TextField(default='')),
                ('caterer_phone', models.TextField(default='')),
                ('caterer_name', models.TextField(default='')),
                ('catering_budget', models.TextField(default='')),
                ('supplies_budget', models.TextField(default='')),
                ('date', models.TextField(default='')),
                ('event_description', models.TextField(blank=True, default='')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='carpool_posts/')),
                ('image_visibility', models.CharField(choices=[('all', 'All Users')], default='all', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
