# Generated by Django 5.0.1 on 2026-04-25 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpost',
            old_name='dropoff',
            new_name='caterer_address',
        ),
        migrations.RenameField(
            model_name='eventpost',
            old_name='dropoff_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='eventpost',
            old_name='notes',
            new_name='event_description',
        ),
        migrations.RenameField(
            model_name='eventpost',
            old_name='name',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='eventpost',
            old_name='pickup',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='eventpost',
            old_name='pickup_time',
            new_name='start_time',
        ),
    ]
