# Generated by Django 5.0.1 on 2026-04-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_eventpost_caterer_name_eventpost_caterer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='host_name',
            field=models.TextField(default=''),
        ),
    ]
