# Generated by Django 5.0.1 on 2026-04-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_eventpost_attendees_eventpost_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='caterer_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='caterer_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='caterer_phone',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='catering_budget',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='supplies_budget',
            field=models.TextField(blank=True, default=''),
        ),
    ]
