# Generated by Django 5.0.1 on 2026-04-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_eventpost_caterer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='catering_budget',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='supplies_budget',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
