# Generated by Django 5.2.5 on 2026-04-27 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowUpRSVPs',
            fields=[
                ('rsvpID', models.AutoField(db_column='RSVPID', primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='status', max_length=10)),
                ('message', models.CharField(db_column='message', max_length=255)),
                ('event', models.ForeignKey(db_column='eventID', on_delete=django.db.models.deletion.CASCADE, to='dashboard.eventpost')),
                ('user', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ShowUp_RSVPs',
            },
        ),
    ]
