# Generated by Django 5.2.7 on 2026-04-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowUpUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userID', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_column='firstName', max_length=100)),
                ('lastName', models.CharField(db_column='lastName', max_length=100)),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=20, null=True)),
                ('birthdate', models.DateField(blank=True, db_column='birthdate', null=True)),
                ('accountCreated', models.DateTimeField(auto_now_add=True, db_column='accountCreated')),
                ('pfp', models.ImageField(blank=True, db_column='pfp', null=True, upload_to='profile_pictures/')),
                ('preferenceID', models.IntegerField(blank=True, db_column='preferenceID', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'ShowUp_Users',
            },
        ),
    ]
