# Generated by Django 5.2.5 on 2026-04-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowUpUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userID', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_column='firstName', max_length=100)),
                ('lastName', models.CharField(db_column='lastName', max_length=100)),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('pfp', models.BinaryField(blank=True, null=True)),
                ('accountCreated', models.DateTimeField(auto_now_add=True, db_column='accountCreated')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ShowUp_Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('preferenceID', models.AutoField(db_column='preferenceID', primary_key=True, serialize=False)),
                ('lightMode', models.CharField(db_column='lightMode', max_length=10)),
                ('notifications', models.BooleanField(db_column='notifications')),
            ],
            options={
                'db_table': 'ShowUp_Preferences',
                'managed': False,
            },
        ),
    ]
