# Generated by Django 5.0.1 on 2026-04-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('preferenceID', models.AutoField(db_column='preferenceID', primary_key=True, serialize=False)),
                ('lightMode', models.CharField(db_column='lightMode', max_length=10)),
                ('notifications', models.BooleanField(db_column='notifications')),
            ],
            options={
                'db_table': 'ShowUp_Preferences',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='showupuser',
            options={'managed': False},
        ),
    ]
